# Global Project Configuration
project_name: "recsys_distribution"
random_seed: 42

# Data Pipeline
data:
  raw_path: "data/raw/sales_dump.csv"
  processed_path: "data/processed/interactions.tfrecord"
  vocab_path: "data/processed/vocabularies"
  test_size: 0.2
  val_size: 0.1
  batch_size: 1024 # Large batch size is better for Two-Tower negative sampling

# Stage 1: Retrieval (Two-Tower)
retrieval:
  embedding_dim: 64
  layer_sizes: [256, 128]
  learning_rate: 0.1
  epochs: 10
  top_k_candidates: 100 # How many items to pass to Stage 2

# Stage 2: Ranking (Deep Learning)
ranking:
  embedding_dim: 32
  layer_sizes: [1024, 512, 256]
  learning_rate: 0.01
  epochs: 20
  dropout_rate: 0.2

  # Diversity Research Params
  diversity_lambda: 0.05 # Weight for the diversity penalty
  diversity_loss_type: "dpp" # Options: 'dpp', 'cosine_penalty'

# Inference / API
serving:
  model_version: "v1"
  final_top_k: 5
